services:
  - type: web
    name: pulse-post-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # This will be set in Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set in Render dashboard
      - key: PORT
        value: 10000
    autoDeploy: true

  - type: web
    name: pulse-post-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
